services:
  db:
    image: postgres:15
    container_name: priorityflow-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gestor_prioridade
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # ðŸ‘ˆ monta o script de inicializaÃ§Ã£o

  backend:
    build: ./backend
    container_name: priorityflow-backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=gestor_prioridade
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - db

volumes:
  pgdata:
